import * as THREE from 'three';

export const FORMAT_LIMITS=Object.freeze({maxImportBytes:256*1024*1024,maxExportTriangles:2_000_000,maxCurvePoints:2_000_000});
export const SUPPORTED_FORMATS=Object.freeze(['gltf','glb','obj','stl','ply','svg','dxf']);
const extOf=name=>(String(name||'').toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'');
const finite=v=>Number.isFinite(v);
const fail=(format,message)=>{throw new Error(`${format.toUpperCase()}: ${message}`);};
const fileBuffer=async file=>{if(!file||!Number.isFinite(file.size))throw new Error('Import requires a File');if(file.size<=0)throw new Error('Import file is empty');if(file.size>FORMAT_LIMITS.maxImportBytes)throw new Error(`Import file exceeds ${FORMAT_LIMITS.maxImportBytes} byte limit`);return file.arrayBuffer();};
const loaderResult=(run,format)=>new Promise((resolve,reject)=>{try{run(resolve,error=>reject(new Error(`${format.toUpperCase()}: ${error?.message||error||'parse failed'}`)));}catch(error){reject(new Error(`${format.toUpperCase()}: ${error?.message||error}`));}});

function validateObject(root,format){let meshes=0,vertices=0,triangles=0;root?.traverse?.(object=>{const geometry=object.geometry,position=geometry?.attributes?.position,index=geometry?.index;if(!position)return;meshes++;vertices+=position.count;triangles+=(index?.count||position.count)/3;for(let i=0;i<position.count;i++)if(!finite(position.getX(i))||!finite(position.getY(i))||!finite(position.getZ(i)))fail(format,'non-finite vertex coordinate');if(index)for(let i=0;i<index.count;i++){const v=index.getX(i);if(!Number.isInteger(v)||v<0||v>=position.count)fail(format,'index is outside the position buffer');}});if(!meshes)fail(format,'file contains no compatible mesh or curve data');return {meshes,vertices,triangles};}

function svgCurves(text){
  const documentValue=new DOMParser().parseFromString(text,'image/svg+xml');if(documentValue.querySelector('parsererror'))fail('svg','malformed XML');
  const curves=[],warnings=[],matrixFor=element=>{const transform=element.getAttribute('transform')||'',m=new DOMMatrix();try{return transform?new DOMMatrix(transform):m;}catch{return m;}},apply=(point,m)=>{const q=new DOMPoint(point[0],point[1]).matrixTransform(m);return [q.x,-q.y,0];};
  const tokenize=d=>(d.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/g)||[]),sampleCubic=(a,b,c,d,count=12)=>Array.from({length:count},(_,i)=>{const t=(i+1)/count,s=1-t;return [s*s*s*a[0]+3*s*s*t*b[0]+3*s*t*t*c[0]+t*t*t*d[0],s*s*s*a[1]+3*s*s*t*b[1]+3*s*t*t*c[1]+t*t*t*d[1]];});
  for(const [pathIndex,path] of [...documentValue.querySelectorAll('path')].entries()){
    const tokens=tokenize(path.getAttribute('d')||'');let i=0,cmd='',cursor=[0,0],start=null,points=[],closed=false;const read=()=>{const n=Number(tokens[i++]);if(!finite(n))fail('svg','path contains an invalid number');return n;},push=p=>{cursor=p;if(!points.length||Math.hypot(points.at(-1)[0]-p[0],points.at(-1)[1]-p[1])>1e-10)points.push(p);};
    while(i<tokens.length){if(/[a-zA-Z]/.test(tokens[i]))cmd=tokens[i++];if(!cmd)fail('svg','path command is missing');const relative=cmd===cmd.toLowerCase(),C=cmd.toUpperCase(),base=cursor.slice();if(C==='M'||C==='L'){const p=[read(),read()];if(relative){p[0]+=base[0];p[1]+=base[1];}push(p);if(C==='M'){start=p.slice();cmd=relative?'l':'L';}}else if(C==='H'){const p=[read()+(relative?base[0]:0),base[1]];push(p);}else if(C==='V'){const p=[base[0],read()+(relative?base[1]:0)];push(p);}else if(C==='C'){const c1=[read(),read()],c2=[read(),read()],end=[read(),read()];if(relative)for(const p of [c1,c2,end]){p[0]+=base[0];p[1]+=base[1];}for(const p of sampleCubic(base,c1,c2,end))push(p);}else if(C==='Q'){const c=[read(),read()],end=[read(),read()];if(relative)for(const p of [c,end]){p[0]+=base[0];p[1]+=base[1];}const c1=[base[0]+(c[0]-base[0])*2/3,base[1]+(c[1]-base[1])*2/3],c2=[end[0]+(c[0]-end[0])*2/3,end[1]+(c[1]-end[1])*2/3];for(const p of sampleCubic(base,c1,c2,end))push(p);}else if(C==='Z'){closed=true;if(start)cursor=start.slice();cmd='';}else{warnings.push(`path ${pathIndex+1}: ${C} was deterministically reduced to its end point`);let end;if(C==='S')end=[tokens[i+2],tokens[i+3]],i+=4;else if(C==='T')end=[tokens[i],tokens[i+1]],i+=2;else if(C==='A')end=[tokens[i+5],tokens[i+6]],i+=7;else fail('svg',`unsupported path command ${C}`);end=end.map(Number);if(relative){end[0]+=base[0];end[1]+=base[1];}push(end);}}
    if(points.length>=2){const matrix=matrixFor(path);curves.push({name:path.getAttribute('id')||`SVG path ${pathIndex+1}`,closed,points:points.map(p=>apply(p,matrix))});}
  }
  for(const [index,poly] of [...documentValue.querySelectorAll('polyline,polygon')].entries()){const nums=(poly.getAttribute('points')||'').match(/[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/g)?.map(Number)||[];if(nums.length%2)fail('svg','polyline has an incomplete coordinate');const matrix=matrixFor(poly),points=[];for(let i=0;i<nums.length;i+=2)points.push(apply([nums[i],nums[i+1]],matrix));if(points.length>=2)curves.push({name:poly.getAttribute('id')||`SVG polyline ${index+1}`,closed:poly.tagName.toLowerCase()==='polygon',points});}
  if(curves.reduce((n,c)=>n+c.points.length,0)>FORMAT_LIMITS.maxCurvePoints)fail('svg','curve point limit exceeded');if(!curves.length)fail('svg','no compatible path/polyline/polygon elements');return {curves,warnings};
}

function dxfData(text){
  const raw=text.replace(/\r/g,'').split('\n'),pairs=[];for(let i=0;i+1<raw.length;i+=2)pairs.push([Number(raw[i].trim()),raw[i+1].trim()]);if(!pairs.length||pairs.some(([code])=>!Number.isInteger(code)))fail('dxf','invalid group-code stream');
  const curves=[],faces=[],warnings=[];let section='',entity=null;const finish=()=>{if(!entity)return;if(entity.type==='LINE'){const a=[+entity.v[10]||0,+entity.v[20]||0,+entity.v[30]||0],b=[+entity.v[11]||0,+entity.v[21]||0,+entity.v[31]||0];curves.push({name:entity.layer||'DXF LINE',closed:false,points:[a,b]});}else if(entity.type==='LWPOLYLINE'){const xs=entity.list[10]||[],ys=entity.list[20]||[],z=+entity.v[38]||0,points=xs.map((x,i)=>[+x,+ys[i]||0,z]);if(points.length>=2)curves.push({name:entity.layer||'DXF polyline',closed:!!((+entity.v[70]||0)&1),points});}else if(entity.type==='3DFACE'){const points=[0,1,2,3].map(k=>[+entity.v[10+k]||0,+entity.v[20+k]||0,+entity.v[30+k]||0]);if(points[3].every((x,k)=>Math.abs(x-points[2][k])<1e-12))points.pop();faces.push({name:entity.layer||'DXF mesh',points});}else if(!['SECTION','ENDSEC','EOF'].includes(entity.type))warnings.push(`unsupported DXF entity ${entity.type}`);entity=null;};
  for(const [code,value] of pairs){if(code===0){finish();if(value==='SECTION'){entity={type:value,v:{},list:{}};continue;}if(value==='ENDSEC'){section='';continue;}if(value==='EOF')break;if(section==='ENTITIES')entity={type:value,v:{},list:{}};else entity={type:value,v:{},list:{}};continue;}if(entity?.type==='SECTION'&&code===2){section=value;continue;}if(!entity||section!=='ENTITIES')continue;if(code===8)entity.layer=value;else{entity.v[code]=value;(entity.list[code]||(entity.list[code]=[])).push(value);}}finish();
  if(curves.reduce((n,c)=>n+c.points.length,0)>FORMAT_LIMITS.maxCurvePoints)fail('dxf','curve point limit exceeded');let root=null;if(faces.length){root=new THREE.Group();root.name='DXF';const byLayer=new Map();for(const face of faces){let rec=byLayer.get(face.name);if(!rec)byLayer.set(face.name,rec={positions:[],indices:[]});const base=rec.positions.length/3;for(const p of face.points)rec.positions.push(...p);rec.indices.push(base,base+1,base+2);if(face.points.length===4)rec.indices.push(base,base+2,base+3);}for(const [name,rec] of byLayer){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(rec.positions,3));geometry.setIndex(rec.indices);geometry.computeVertexNormals();root.add(new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xb8c1ca,side:THREE.DoubleSide,name})));}}if(!curves.length&&!root)fail('dxf','no compatible LINE/LWPOLYLINE/3DFACE entities');return {root,curves,warnings};
}

export async function importExternalFile(file){
  const format=extOf(file?.name);if(!SUPPORTED_FORMATS.includes(format))throw new Error(`Unsupported import format .${format||'?'}`);const buffer=await fileBuffer(file),warnings=[];let root=null,curves=[];
  if(format==='gltf'||format==='glb'){if(format==='gltf'){let json;try{json=JSON.parse(new TextDecoder().decode(buffer));}catch{fail(format,'malformed JSON');}if(json?.asset?.version!=='2.0')fail(format,'only glTF 2.0 is supported');for(const item of [...(json.buffers||[]),...(json.images||[])])if(item.uri&&!item.uri.startsWith('data:'))fail(format,`external resource ${item.uri} requires a self-contained GLB/data URI`);}else{if(buffer.byteLength<20)fail(format,'truncated GLB header');const view=new DataView(buffer);if(view.getUint32(0,true)!==0x46546c67||view.getUint32(4,true)!==2||view.getUint32(8,true)!==buffer.byteLength)fail(format,'invalid GLB header or declared length');}const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const gltf=await loaderResult((ok,bad)=>new GLTFLoader().parse(buffer,'',ok,bad),format);root=gltf.scene||gltf.scenes?.[0];if(!root)fail(format,'scene is missing');}
  else if(format==='obj'){const text=new TextDecoder().decode(buffer);if(!/^\s*v\s+[-+0-9.]/mi.test(text)||!/^\s*f\s+\S+\s+\S+\s+\S+/mi.test(text))fail(format,'file contains no complete vertex/face records');if(/^\s*mtllib\s+/mi.test(text))warnings.push('MTL companion files are not loaded by single-file import; geometry and inline material groups were preserved');const {OBJLoader}=await import('three/addons/loaders/OBJLoader.js');try{root=new OBJLoader().parse(text);}catch(error){fail(format,error.message||'parse failed');}}
  else if(format==='stl'){const textPrefix=new TextDecoder().decode(buffer.slice(0,Math.min(buffer.byteLength,4096))),ascii=/^\s*solid\b/i.test(textPrefix);if(ascii){const text=new TextDecoder().decode(buffer);if(!/facet\s+normal\s+[-+0-9.e]+\s+[-+0-9.e]+\s+[-+0-9.e]+[\s\S]*outer\s+loop[\s\S]*(?:vertex\s+[-+0-9.e]+\s+[-+0-9.e]+\s+[-+0-9.e]+[\s\S]*){3}endloop[\s\S]*endfacet/i.test(text))fail(format,'truncated or malformed ASCII STL');}else{if(buffer.byteLength<84)fail(format,'truncated binary STL header');const count=new DataView(buffer).getUint32(80,true);if(84+count*50!==buffer.byteLength)fail(format,'binary STL length does not match triangle count');}const {STLLoader}=await import('three/addons/loaders/STLLoader.js');let geometry;try{geometry=new STLLoader().parse(buffer);}catch(error){fail(format,error.message||'parse failed');}root=new THREE.Group();root.add(new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xb8c1ca,side:THREE.DoubleSide,name:'STL material'})));warnings.push('STL contains tessellated geometry only; hierarchy, materials, units and up axis are not encoded');}
  else if(format==='ply'){const prefix=new TextDecoder().decode(buffer.slice(0,Math.min(buffer.byteLength,65536))),end=prefix.indexOf('end_header');if(!prefix.startsWith('ply')||end<0)fail(format,'missing PLY header/end_header');const formatLine=prefix.match(/^format\s+(\S+)/m)?.[1],vertexCount=Number(prefix.match(/^element\s+vertex\s+(\d+)/m)?.[1]||0);if(!vertexCount)fail(format,'vertex element is missing or empty');if(formatLine==='ascii'){const body=prefix.slice(end+'end_header'.length).trim().split(/\r?\n/);if(body.length<vertexCount)fail(format,'truncated ASCII vertex list');for(let i=0;i<vertexCount;i++){const xyz=body[i].trim().split(/\s+/).slice(0,3).map(Number);if(xyz.length<3||xyz.some(x=>!finite(x)))fail(format,'non-finite or incomplete ASCII vertex');}}else if(!['binary_little_endian','binary_big_endian'].includes(formatLine))fail(format,'unsupported PLY encoding');const {PLYLoader}=await import('three/addons/loaders/PLYLoader.js');let geometry;try{geometry=new PLYLoader().parse(buffer);}catch(error){fail(format,error.message||'parse failed');}if(!geometry.attributes.normal)geometry.computeVertexNormals();root=new THREE.Group();root.add(new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xb8c1ca,vertexColors:!!geometry.attributes.color,side:THREE.DoubleSide,name:'PLY material'})));warnings.push('PLY contains a flat element list; hierarchy and transforms are unavailable');}
  else if(format==='svg'){const parsed=svgCurves(new TextDecoder().decode(buffer));curves=parsed.curves;warnings.push(...parsed.warnings,'SVG units are imported 1 unit = 1 mm; Y is converted from down to up');}
  else if(format==='dxf'){const parsed=dxfData(new TextDecoder().decode(buffer));root=parsed.root;curves=parsed.curves;warnings.push(...parsed.warnings,'DXF coordinates are imported as millimetres in right-handed Y-up Frame coordinates');}
  const diagnostics=root?validateObject(root,format):{meshes:0,vertices:0,triangles:0};return {format,root,curves,warnings,diagnostics,bytes:buffer.byteLength};
}

function triangleCount(root){let triangles=0;root.traverse(object=>{const g=object.geometry,p=g?.attributes?.position;if(p)triangles+=(g.index?.count||p.count)/3;});return triangles;}
function mtlText(root){const materials=new Set();root.traverse(object=>{for(const material of object.material?(Array.isArray(object.material)?object.material:[object.material]):[])materials.add(material);});const lines=['# FRAME OBJ/MTL export',''];for(const material of materials){const name=(material.name||`material_${material.id}`).replace(/[^\w.\-]+/g,'_'),c=material.color||new THREE.Color(1,1,1),e=material.emissive||new THREE.Color(0,0,0);lines.push(`newmtl ${name}`,`Kd ${c.r} ${c.g} ${c.b}`,`Ke ${e.r} ${e.g} ${e.b}`,`d ${material.opacity??1}`,`Pr ${material.roughness??.5}`,`Pm ${material.metalness??0}`,'');}return lines.join('\n');}
function svgText(curves){if(!curves.length)fail('svg','no planar spline curves to export');let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const c of curves)for(const p of c.points){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,-p[1]);maxY=Math.max(maxY,-p[1]);}const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])),paths=curves.map(c=>`  <path id="${esc(c.name)}" d="M ${c.points.map((p,i)=>`${i?'L ':''}${p[0]} ${-p[1]}`).join(' ')}${c.closed?' Z':''}" fill="none" stroke="black"/>`);return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${Math.max(1,maxX-minX)} ${Math.max(1,maxY-minY)}">\n${paths.join('\n')}\n</svg>\n`;}
function dxfText(root,curves){const lines=['0','SECTION','2','HEADER','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES'],emit=(...items)=>lines.push(...items.map(String));for(const curve of curves){const z=curve.points[0]?.[2]||0,planar=curve.points.every(p=>Math.abs((p[2]||0)-z)<1e-8);if(planar){emit(0,'LWPOLYLINE',8,curve.name||'SPLINE',90,curve.points.length,70,curve.closed?1:0,38,z);for(const p of curve.points)emit(10,p[0],20,p[1]);}else for(let i=1;i<curve.points.length+(curve.closed?1:0);i++){const a=curve.points[(i-1)%curve.points.length],b=curve.points[i%curve.points.length];emit(0,'LINE',8,curve.name||'SPLINE',10,a[0],20,a[1],30,a[2],11,b[0],21,b[1],31,b[2]);}}root.updateMatrixWorld(true);const p=new THREE.Vector3();root.traverse(object=>{const g=object.geometry,pos=g?.attributes?.position,idx=g?.index;if(!object.isMesh||!pos)return;const count=idx?idx.count:pos.count;for(let i=0;i+2<count;i+=3){const vertices=[0,1,2].map(k=>p.fromBufferAttribute(pos,idx?idx.getX(i+k):i+k).applyMatrix4(object.matrixWorld).toArray());emit(0,'3DFACE',8,object.name||'MESH');for(let k=0;k<4;k++){const q=vertices[Math.min(k,2)];emit(10+k,q[0],20+k,q[1],30+k,q[2]);}}});emit(0,'ENDSEC',0,'EOF');return lines.join('\n')+'\n';}

export async function exportExternalScene({root,curves=[]},format,options={}){
  format=String(format||'').toLowerCase().replace(/^\./,'');if(!SUPPORTED_FORMATS.includes(format))throw new Error(`Unsupported export format .${format||'?'}`);const triangles=triangleCount(root);if(triangles>FORMAT_LIMITS.maxExportTriangles)throw new Error(`Export contains ${triangles} triangles; limit is ${FORMAT_LIMITS.maxExportTriangles}`);const warnings=[];let data,mime,name=`scene.${format}`,attachments=[];
  if(format==='gltf'||format==='glb'){const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');data=await loaderResult((ok,bad)=>new GLTFExporter().parse(root,ok,bad,{binary:format==='glb',embedImages:true,onlyVisible:false,trs:false}),format);if(format==='gltf')data=JSON.stringify(data,null,2);mime=format==='glb'?'model/gltf-binary':'model/gltf+json';}
  else if(format==='obj'){const {OBJExporter}=await import('three/addons/exporters/OBJExporter.js');data=new OBJExporter().parse(root);mime='text/plain';attachments=[{name:'scene.mtl',blob:new Blob([mtlText(root)],{type:'text/plain'})}];warnings.push('OBJ is tessellated and transform-flattened; hierarchy/instances are represented as named objects. MTL is a companion file.');}
  else if(format==='stl'){const {STLExporter}=await import('three/addons/exporters/STLExporter.js');data=new STLExporter().parse(root,{binary:options.binary!==false});mime=options.binary===false?'model/stl':'application/octet-stream';warnings.push('STL exports tessellated triangles only; names, hierarchy, materials, normals/UV and units metadata are unavailable. Coordinates remain millimetres.');}
  else if(format==='ply'){const {PLYExporter}=await import('three/addons/exporters/PLYExporter.js');data=await loaderResult((ok,bad)=>new PLYExporter().parse(root,ok,bad,{binary:options.binary!==false,excludeAttributes:options.excludeAttributes||[]}),format);mime=options.binary===false?'text/plain':'application/octet-stream';warnings.push('PLY exports a flattened element list; hierarchy, instances and transforms are baked.');}
  else if(format==='svg'){data=svgText(curves);mime='image/svg+xml';warnings.push('Only planar spline approximations are exported; mesh objects and non-planar curves are omitted.');}
  else if(format==='dxf'){data=dxfText(root,curves);mime='application/dxf';warnings.push('DXF subset is LINE plus 3DFACE. Splines are deterministically tessellated; materials, textures and hierarchy are omitted.');}
  const blob=data instanceof Blob?data:new Blob([data],{type:mime});return {format,name,blob,attachments,warnings,bytes:blob.size,triangles,curves:curves.length};
}
