import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import{buildTopologyWork}from '../../native-source/topology-islands.mjs';
import {rigidIslandEligibilityWork} from '../../native-source/gpu-island-preview.mjs';
const ctx={Set,Map,WeakMap,Uint32Array,Float64Array,console,performance};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../rigid-component-preview.mjs',import.meta.url),'utf8'),ctx);
const drain=w=>{let s,yields=0,longest=0,start=performance.now();do{s=w.next();longest=Math.max(longest,performance.now()-start);start=performance.now();if(!s.done)yields++;}while(!s.done);return{value:s.value,yields,longest};};
const build=(pa,ids)=>{const slot=new Int32Array(pa.length/3);ids.forEach((id,k)=>slot[id]=k+1);const t={pa,p:{count:pa.length/3},ids:new Uint32Array(ids),slot};assert(drain(ctx.frameRigidBuildAliasGuard(t)).value);return t;};
const out={cpuOnly:true,pass:[],findings:[],cost:[]};
let seed=7;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296),pa=Float32Array.from({length:3000},()=>Math.fround((rand()-.5)*100)),t=build(pa,Array.from({length:100},(_,i)=>i));const key=(a,i)=>[0,1,2].map(j=>Math.round(a[i*3+j]*1e5)).join(',');const reference=new Set(Array.from({length:900},(_,i)=>key(pa,i+100)));
for(let i=0;i<1000;i++){const x=i%2?pa[(100+i%900)*3]:Math.fround((rand()-.5)*100),y=i%2?pa[(100+i%900)*3+1]:Math.fround((rand()-.5)*100),z=i%2?pa[(100+i%900)*3+2]:Math.fround((rand()-.5)*100);assert.equal(t.aliasGuard.find(Math.round(x*1e5),Math.round(y*1e5),Math.round(z*1e5)),reference.has([x,y,z].map(v=>Math.round(v*1e5)).join(',')));}out.pass.push('1000 exact numeric lookup controls match pinned Number/string reference');
const simple=build(new Float32Array([0,0,0,1,0,0,0,1,0,10,0,0,11,0,0,10,1,0]),[0,1,2]),before=simple.pa.slice(0,9),contact=before.slice();contact.set([10,0,0],0);assert(ctx.frameRigidAliasSafe(simple,before));assert(!ctx.frameRigidAliasSafe(simple,contact));assert(ctx.frameRigidAliasSafe(simple,before));assert(!ctx.frameRigidAliasSafe(simple,contact));out.pass.push('New outside contact, moving away and Undo/Redo coordinate values reclassify correctly');
const over={p:{count:3000000},ids:new Uint32Array(1)};assert.equal(drain(ctx.frameRigidBuildAliasGuard(over)).value,false);out.pass.push('64MiB budget rejects before table allocation');
// A valid unused logical alias is included by the stock selected-vertex policy at admission.
const positions=new Float32Array([0,0,0,1,0,0,0,1,0,4e-6,0,0]),indices=new Uint32Array([0,1,2]),faces=new Set([0]);const topo=drain(buildTopologyWork({positions,indices})).value,gate=drain(rigidIslandEligibilityWork(topo,indices,faces)).value;assert(gate.eligible);assert.deepEqual([...gate.ids],[0,1,2,3]);const alias=build(positions,[...gate.ids]),after=positions.slice();for(let i=0;i<4;i++)after[i*3]+=2e-6;assert(!ctx.frameRigidAliasSafe(alias,after));const fresh=drain(rigidIslandEligibilityWork(drain(buildTopologyWork({positions:after,indices})).value,indices,faces)).value;assert(fresh.eligible);assert.deepEqual([...fresh.ids],[0,1,2]);out.pass.push('Previously selected alias split invalidates cached preparation; moving back restores safe classification');assert(ctx.frameRigidAliasSafe(alias,positions));const merged=positions.slice();merged.set(merged.subarray(0,3),3);assert(!ctx.frameRigidAliasSafe(alias,merged));assert(ctx.frameRigidAliasSafe(alias,positions));out.pass.push('New within-selected merge invalidates reuse; Undo restores admission');
// Deterministic collision family: large finite Float32 x; quantized low 32 bits all zero.
for(const count of[2048,4096,8192]){const p=new Float32Array((count+1)*3);p[1]=1;for(let i=1;i<=count;i++)p[i*3]=i*4294967296;const slot=new Int32Array(count+1);slot[0]=1;const r={pa:p,p:{count:count+1},ids:new Uint32Array([0]),slot},start=performance.now(),built=drain(ctx.frameRigidBuildAliasGuard(r));assert(built.value);out.cost.push({vertices:count,ms:performance.now()-start,longestCooperativeSliceMS:built.longest,bytes:r.aliasGuard.bytes});}
console.log(JSON.stringify(out,null,2));
