import fs from 'node:fs';import assert from 'node:assert/strict';import vm from 'node:vm';
import * as THREE from '../../modules/frame-three-core.9edde002b066a9a05676.js';
import * as M from '../../native-source/gpu-island-preview.mjs';
const out={hardwareAcceptance:false,guards:[],resources:[],tracking:[]};
const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array([0,0,0,1,0,0,0,1,0,1,1,0]),3));g.setAttribute('normal',new THREE.BufferAttribute(new Float32Array([0,0,1,0,0,1,0,0,1,0,0,1]),3));g.setIndex(new THREE.BufferAttribute(new Uint32Array([0,1,2,2,1,3]),1));
const mesh=new THREE.Mesh(g),entry={faces:new Set([0,1]),vertices:new Set(),edges:new Set()},node={},device={},pool={disposed:false},owner={device,pool,generation:1,state:'ready'},engine={owner,device,disposed:false},lease={owner,device,generation:1,isCurrent:()=>true},bridge={engine,device,lease,disposed:false},renderer={nativeEngine:engine,bridge};
const ctx={THREE2:THREE,Float32Array,Uint32Array,Uint16Array,Map,Set,WeakMap,console,performance,DOMException,polyFocusActive:()=>true,polyElementMode:'face',vertexTools:{soft:{active:false}},uvMode:false,uvEdit:null,editPivot:false,polyPivotMatrix:null,frameChannels:new Map(),vpState:{renderer},polySelection:{items:new Map([['mesh',entry]])},pickMeshes:new Map([['mesh',mesh]]),OBJ:new Map([['mesh',node]]),frameMorphTag:()=>false,framePolySelectionRevision:3,frameAnimationRevision:2};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../rigid-component-preview.mjs',import.meta.url),'utf8'),ctx);
const p=g.attributes.position,n=g.attributes.normal,index=g.index,t={h:'mesh',entry,mesh,node,g,p,n,index,pa:p.array,na:n.array,ia:index.array,pv:p.version,nv:n.version,iv:index.version,faces:entry.faces,vertices:entry.vertices,edges:entry.edges,faceIDs:new Uint32Array([0,1]),selectionRevision:3,selectionSets:ctx.frameRigidSetSnapshots([entry.faces,entry.vertices,entry.edges]),...ctx.frameRigidOwnerSnapshot(),eligible:true,disposed:false,status:'ready',idSet:new Set([0,1,2,3])};ctx.frameRigidPrepared=t;const session={source:ctx.frameRigidTransactionSnapshot(t),discarded:false};assert(ctx.frameRigidSelection(t)&&ctx.frameRigidTransactionCurrent(session));
function reject(name,change,restore,{prepared=true}={}){try{change();assert(!ctx.frameRigidTransactionCurrent(session),name);if(prepared)assert(!ctx.frameRigidSelection(t),name);out.guards.push({name,pass:true});}finally{restore();t.selectionSets=ctx.frameRigidSetSnapshots([entry.faces,entry.vertices,entry.edges]);session.source.selectionSets=ctx.frameRigidSetSnapshots([entry.faces,entry.vertices,entry.edges]);}assert(ctx.frameRigidTransactionCurrent(session),name+' restored');assert(ctx.frameRigidSelection(t),name+' prepared restored');}
reject('same Set removal',()=>entry.faces.delete(1),()=>entry.faces.add(1));reject('same Set equal-size substitution',()=>{entry.faces.delete(1);entry.faces.add(2);},()=>{entry.faces.delete(2);entry.faces.add(1);});
reject('owner generation',()=>owner.generation++,()=>owner.generation--);reject('lease generation',()=>lease.generation++,()=>lease.generation--);reject('lease identity',()=>bridge.lease={...lease},()=>bridge.lease=lease);reject('owner identity',()=>engine.owner={...owner},()=>engine.owner=owner);reject('engine device',()=>engine.device={},()=>engine.device=device);reject('owner lost',()=>owner.state='lost',()=>owner.state='ready');reject('pool disposed',()=>pool.disposed=true,()=>pool.disposed=false);reject('lease current false',()=>lease.isCurrent=()=>false,()=>lease.isCurrent=()=>true);
reject('source geometry replaced',()=>mesh.geometry=g.clone(),()=>mesh.geometry=g);reject('source attribute version',()=>p.version++,()=>p.version--);reject('selection revision',()=>ctx.framePolySelectionRevision++,()=>ctx.framePolySelectionRevision--);reject('animation revision',()=>ctx.frameAnimationRevision++,()=>ctx.frameAnimationRevision--,{prepared:false});reject('transaction world matrix',()=>{mesh.position.x=1;mesh.updateMatrixWorld(true);},()=>{mesh.position.x=0;mesh.updateMatrixWorld(true);},{prepared:false});
// Context invalidation must reject an already admitted transaction.
for(const [name,change,restore]of[['soft selection enabled',()=>ctx.vertexTools.soft.active=true,()=>ctx.vertexTools.soft.active=false],['UV edit entered',()=>ctx.uvEdit={},()=>ctx.uvEdit=null],['pivot editing entered',()=>ctx.editPivot=true,()=>ctx.editPivot=false],['channel selection entered',()=>ctx.frameChannels.set('x',{}),()=>ctx.frameChannels.clear()],['UV mode enabled',()=>ctx.uvMode=true,()=>ctx.uvMode=false],['morph appeared',()=>ctx.frameMorphTag=()=>true,()=>ctx.frameMorphTag=()=>false],['pivot matrix changed',()=>ctx.polyPivotMatrix=new THREE.Matrix4().elements,()=>ctx.polyPivotMatrix=null]])reject(name,change,restore,{prepared:false});
// Version guards are exact for per-instance mutations; no global prototype patch.
const originalMethods={add:Set.prototype.add,delete:Set.prototype.delete,clear:Set.prototype.clear},tracked=new Set([0,1]),row=ctx.frameRigidSetVersion(tracked),snapshot=ctx.frameRigidSetSnapshots([tracked]);assert.equal(typeof row.version,'bigint');assert.deepEqual(Object.keys(tracked),[]);assert.equal(tracked.add(1),tracked);assert.equal(row.version,0n);assert.equal(tracked.delete(99),false);assert.equal(row.version,0n);assert.equal(tracked.add(2),tracked);assert.equal(row.version,1n);assert(!ctx.frameRigidSetSnapshotsCurrent(snapshot));tracked.delete(2);assert.equal(row.version,2n);assert(!ctx.frameRigidSetSnapshotsCurrent(snapshot));tracked.clear();assert.equal(row.version,3n);tracked.clear();assert.equal(row.version,3n);for(const k of Object.keys(originalMethods))assert.equal(Set.prototype[k],originalMethods[k]);out.tracking.push('BigInt monotonic versions; duplicate/absent no-ops; clear; Set method return values; non-enumerability; global prototype untouched');
const fresh=ctx.frameRigidSetSnapshots([tracked]),originalAdd=tracked.add;tracked.add=function(v){return this;};assert(!ctx.frameRigidSetSnapshotsCurrent(fresh));assert.throws(()=>ctx.frameRigidSetVersion(tracked),e=>e.name==='AbortError');tracked.add=originalAdd;out.tracking.push('Mutation-method replacement rejected');
let membershipReads=0;const has=entry.faces.has;entry.faces.has=function(v){membershipReads++;return has.call(this,v);};for(let i=0;i<100;i++){assert(ctx.frameRigidSelection(t));assert(ctx.frameRigidTransactionCurrent(session));}assert.equal(membershipReads,0);assert(ctx.frameRigidSelection(t,true));assert(ctx.frameRigidTransactionCurrent(session,true));assert.equal(membershipReads,4);entry.faces.has=has;out.tracking.push('100 hot guard pairs perform zero membership reads; exact boundaries perform all membership reads');
// Prototype bypass is absent from audited stock callers; exact commit-boundary check still catches it.
Set.prototype.delete.call(entry.faces,1);Set.prototype.add.call(entry.faces,2);assert(ctx.frameRigidTransactionCurrent(session));assert(!ctx.frameRigidTransactionCurrent(session,true));assert(!ctx.frameRigidSelection(t,true));Set.prototype.delete.call(entry.faces,2);Set.prototype.add.call(entry.faces,1);out.tracking.push('Exact boundary rejects same-count direct-prototype bypass (not a production caller)');
// Constructor faults before initialize: every acquired reference must be released.
for(let at=1;at<=5;at++){let acquired=0,released=0,destroyed=0,calls=0;const d={queue:{},createBuffer(){if(++calls===at)throw Error('fault');return{destroy(){destroyed++;}};}},pp={device:d,borrow(){if(++calls===at)throw Error('fault');acquired++;return{buffer:{}};},release(){released++;}};await assert.rejects(M.GpuRigidIslandPreview.create({device:d,pool:pp,positions:new Float32Array(9),extras:new Float32Array(27),ids:new Uint32Array([0])}),/fault/);assert.equal(acquired,released);out.resources.push({name:'constructor allocation failure '+at,acquired,released,pass:true});}
// Stale cleanup cannot unregister a replacement geometry adapter.
let valid=true;const numeric={positions:p.array.slice(),extras:new Float32Array(p.count*9),indices:index.array,vertexCount:p.count};const old=M.registerRigidGpuGeometry(g,numeric,{isCurrent:()=>valid});valid=false;const current=M.registerRigidGpuGeometry(g,numeric);assert.notEqual(old,current);assert.equal(M.unregisterRigidGpuGeometry(g,old),false);assert(M.captureRigidGpuGeometry(g));assert.equal(M.unregisterRigidGpuGeometry(g,current),true);out.resources.push({name:'expected-entry unregister isolation',pass:true});
console.log(JSON.stringify(out,null,2));
