import fs from'node:fs';import vm from'node:vm';import assert from'node:assert/strict';import{createRequire}from'node:module';import * as THREE from'../../modules/frame-three-core.9edde002b066a9a05676.js';
const ts=createRequire(import.meta.url)(process.env.FRAME_TYPESCRIPT||'typescript'),source=fs.readFileSync(new URL('../../'+JSON.parse(fs.readFileSync(new URL('../build-manifest.json',import.meta.url))).productionEditor,import.meta.url),'utf8');
function functions(s){const ast=ts.createSourceFile('editor.mjs',s,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);return new Map(ast.statements.filter(ts.isFunctionDeclaration).filter(n=>n.name).map(n=>[n.name.text,n.getText(ast)]));}const f=functions(source);
const out={cpuOnly:true,passed:[],failures:[]},make=normals=>{const g={positions:new Float32Array([0,0,0,1,0,0,0,1,0,7,8,9]),indices:new Uint32Array([0,1,2])};if(normals)g.normals=new Float32Array([.1,.2,.3,.4,.5,.6,.7,.8,.9,1,0,0]);return{nodes:[['mesh',{geometry:g}]],materials:[]};};
function context(fixture){const ctx={THREE2:THREE,THREE_TEST:THREE,Float32Array,Float64Array,Uint32Array,Uint16Array,WeakRef,WeakMap,Map,Set,ArrayBuffer,console,fixture,CREASE_COS:.5,HASH_PARAM_DEFAULTS:{},UNITS:[],LAYER_OBJ:1,defaultMatHash:'d',getThreeMat:()=>new THREE.MeshBasicMaterial(),frameNative:{captureRigidAuthoringAttribute:()=>null},polygonCreaseCache:new WeakMap(),NativeHash:{inspectContainer:()=>({decodedBytes:5000000}),decodeContainer:async()=>fixture},frameComputeBudget:{acquire:async()=>()=>{}},document:{querySelector:()=>({textContent:JSON.stringify({imports:{'frame-three-core':'file:///module.mjs'}})}),baseURI:'file:///root.html'},Blob:class{constructor(parts){this.parts=parts;}},URL:class extends URL{static createObjectURL(blob){ctx.workerSource=blob.parts.join('');return'blob:mock';}static revokeObjectURL(){}}};vm.createContext(ctx);const names=['buildRenderMesh','polygonCreaseData','packedGeometryAttribute','framePolygonAttributeArray','polygonShadingAllowed','normalizeCreaseTopology','frameContourOriginValidate','frameCreateContourOriginStore','triangleMaterialIndex','markPolygonCreaseGeometry','polygonCreaseGeometryCurrent','initCreaseRender','prepareNativeScene'];for(const n of names)vm.runInContext(f.get(n),ctx);vm.runInContext('function validateShareViewport(){};function createNativeHashCodec(){return{decodeContainer:async()=>fixture};};var frameContourOrigins=frameCreateContourOriginStore();',ctx);
 ctx.Worker=class{constructor(){this.source=ctx.workerSource;}postMessage(bytes){const worker={THREE_TEST:THREE,Float32Array,Float64Array,Uint32Array,Uint16Array,WeakRef,WeakMap,Map,Set,ArrayBuffer,console,fixture,self:{postMessage:data=>this.onmessage({data})}};vm.createContext(worker);vm.runInContext(this.source.replace(/^const threeReady=import\([^\n]+\);let THREE2;/,'const threeReady=Promise.resolve(THREE_TEST);let THREE2;'),worker);Promise.resolve(worker.self.onmessage({data:bytes})).catch(e=>this.onerror({message:e.message}));}terminate(){}};return ctx;}
for(const authored of[true,false]){
 const fixture=make(authored),ctx=context(fixture),input=fixture.nodes[0][1].geometry,mesh=ctx.buildRenderMesh({geom:input,selects:[]});if(authored){ctx.initCreaseRender(mesh);assert.deepEqual(mesh.geometry.attributes.position.array,input.positions);assert.deepEqual(mesh.geometry.attributes.normal.array,input.normals);assert.deepEqual(mesh.geometry.index.array,input.indices);out.passed.push('Main no-Worker authored normal/index arrays exact through initCreaseRender');}else{assert(mesh.geometry.attributes.normal);out.passed.push('Main legacy branch computes normals');}
 try{const scene=await ctx.prepareNativeScene(new Uint8Array());const q=scene.nodes[0][1].geometry;if(authored){assert.deepEqual(q.prepared.normals,input.normals);assert.deepEqual(q.prepared.indices,input.indices);assert.deepEqual(q.prepared.positions,input.positions);out.passed.push('Actual generated worker source preserves authored position/normal/index arrays with no frameNative namespace');}else out.passed.push('Generated worker legacy path');}catch(e){out.failures.push({case:authored?'worker authored':'worker legacy missing normals',error:String(e),scope:'Generated production worker source, CPU context; codec decoding stubbed to fixture'});}
 delete ctx.Worker;assert.equal(await ctx.prepareNativeScene(new Uint8Array()),fixture);out.passed.push('No-Worker prepare path returns decoded scene for '+(authored?'authored':'legacy'));
}
console.log(JSON.stringify(out,null,2));
