// Run in a checkout: node editor-source/tests/lifecycle.mjs
// An optional checkout-root argument supports reviewing this standalone file before installation.
// CPU control flow only: real Three math, mocked renderer/GPU/UI effects, stdout JSON, no writes.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {resolve,sep} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const sourceBase=process.argv[2]?pathToFileURL(resolve(process.argv[2],'editor-source')+sep):new URL('../',import.meta.url);
const root=new URL('../',sourceBase),manifest=JSON.parse(fs.readFileSync(new URL('build-manifest.json',sourceBase),'utf8'));
const source=fs.readFileSync(new URL('rigid-component-preview.mjs',sourceBase),'utf8');
const editorBytes=fs.readFileSync(new URL(manifest.productionEditor,root));
assert.equal(editorBytes.byteLength,manifest.productionBytes,'Production editor byte count');
assert.equal(createHash('sha256').update(editorBytes).digest('hex'),manifest.productionSHA256,'Production editor SHA-256');
const editor=editorBytes.toString('utf8');assert(editor.includes(source.trim()),'Helper must be verbatim in production editor');
const THREE2=await import(new URL('modules/frame-three-core.9edde002b066a9a05676.js',root));
const report={scope:'Source-extracted CPU control flow with real Three math and mocked GPU/UI effects; not pointer/WebGPU acceptance',productionSHA256:manifest.productionSHA256,passed:[],remaining:[],errors:[]};
function env(){const logs=[],device={},pool={disposed:false},owner={state:'ready',generation:1,device,pool},engine={owner,device,geometryCache:{rows:new WeakMap()}},lease={owner,device,generation:1,isCurrent:()=>true},bridge={engine,device,lease},renderer={nativeEngine:engine,bridge,domElement:{releasePointerCapture:id=>logs.push(['release',id])}};let gizmo=new THREE2.Matrix4().elements.slice();
 const c={console:{error:()=>{}},THREE2,Float32Array,Uint32Array,Uint16Array,Int32Array,Set,Map,WeakMap,performance,DOMException,Promise,polySelection:{items:new Map(),...Object.fromEntries(['face','faceBack','edge','vertex'].map(k=>[k,{matrix:new THREE2.Matrix4(),matrixAutoUpdate:true}]))},polyMode:true,splineMode:false,componentFocus:'poly',polyElementMode:'face',polyFocusActive:()=>true,frameChannels:new Set(),framePolySelectionRevision:1,frameAnimationRevision:1,vertexTools:{soft:{active:false}},uvMode:false,uvEdit:null,editPivot:false,splineFocusActive:()=>false,coordMode:'world',polyPivotMatrix:null,OBJ:new Map(),frameMorphTag:()=>null,pickMeshes:new Map(),markPolygonCreaseGeometry(){},objectPickBVHs:new WeakMap(),frameSTLPickTrees:new WeakMap(),vertexGroupCache:new WeakMap(),vertexGroupOfCache:new WeakMap(),frameGetNativeTopologyCache:()=>({invalidate(){}}),frameNative:{unregisterRigidGpuGeometry(){logs.push(['unregister']);},touchRigidGpuGeometry:e=>{if(e.live===false)throw new DOMException('disposed','AbortError');e.revision++;}},getGizmoWorldArray:()=>gizmo.slice(),setGizmoFromMatrix:a=>{gizmo=a.slice();},vpState:{renderer},gizDrag:{mode:'move'},_gizStart:()=>logs.push(['cpu-start']),_gizEnd:()=>logs.push(['cpu-end']),bridgeTransform:()=>logs.push(['cpu-transform']),gizBeforePoly:null,gizBeforePolyGeom:null,gizBeforePolySel:null,gizBeforePolyPivot:null,gizBeforeGizmo:null,gizBeforePolySoft:null,polyExactEdgeVertices:null,frameClearPolygonGizmoMove(){},frozenSignsPerView:null,scheduleRender(){},updateHUD(){},placeGizmoForSelection(){},frameDrainSelectionWork:w=>{let q;do{q=w.next();}while(!q.done);return q.value;},framePolySelectionBuffers:function*(){return{};},frameInstallPolySelectionBuffers(){},undoStack:[],redoStack:[],sceneStateToken:1,sceneMutationSequence:1,sceneWorkStartedAt:1};c.pushCmd=x=>{c.undoStack.push(x);c.redoStack.length=0;c.sceneStateToken++;};vm.createContext(c);vm.runInContext(source,c);return{c,logs};}
function geometry(){const g=new THREE2.BufferGeometry();g.setAttribute('position',new THREE2.BufferAttribute(Float32Array.of(0,0,0,1,0,0,0,1,0,10,0,0,11,0,0,10,1,0),3));g.setAttribute('normal',new THREE2.BufferAttribute(Float32Array.of(0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1),3));g.setIndex(new THREE2.BufferAttribute(Uint32Array.of(0,1,2,3,4,5),1));return g;}
function fixture(c,logs){const g=geometry(),p=g.attributes.position,n=g.attributes.normal,index=g.index,node={},mesh={geometry:g,isMesh:true,userData:{},matrixWorld:new THREE2.Matrix4(),updateMatrixWorld(){}},entry={faces:new Set([0]),edges:new Set(),vertices:new Set()};c.pickMeshes.set('h',mesh);c.OBJ.set('h',node);c.polySelection.items.set('h',entry);const t={h:'h',entry,mesh,node,g,p,n,index,pa:p.array,na:n.array,ia:index.array,pv:p.version,nv:n.version,iv:index.version,faces:entry.faces,edges:entry.edges,vertices:entry.vertices,faceIDs:Uint32Array.of(0),selectionRevision:1,ids:Uint32Array.of(0,1,2),slot:Int32Array.of(1,2,3,0,0,0),ranges:[[0,3]],disposed:false,status:'ready',eligible:true,...c.frameRigidOwnerSnapshot(),originalPositions:p.array.slice(),originalNormals:n.array.slice(),indexSeed:index.array.slice(),numeric:{positions:p.array.slice(),extras:new Float32Array(p.count*9)},adapter:{live:true,positionView:null,normalView:null,revision:0},promise:Promise.resolve(true)};for(let i=0;i<p.count;i++)t.numeric.extras.set(n.array.subarray(i*3,i*3+3),i*9);t.gpu={dispose:()=>logs.push(['gpu-dispose']),writeAuthoringRanges:()=>logs.push(['gpu-write'])};t.selectionSets=c.frameRigidSetSnapshots([entry.faces,entry.vertices,entry.edges]);for(const _ of c.frameRigidBuildAliasGuard(t)){}t.aliasSafe=c.frameRigidAliasSafe(t);c.frameRigidPrepared=t;c.frameRigidExactBounds(t);return t;}
function session(c,t,{ready=true,released=true,cancel=false,kind='gpu'}={}){let abortResolve;const abortPromise=new Promise(r=>abortResolve=r),s={t,source:c.frameRigidTransactionSnapshot(t),kind,event:{type:'pointerdown',pointerId:1},drag:c.gizDrag,gizmo:new THREE2.Matrix4().elements.slice(),afterGizmo:new THREE2.Matrix4().makeTranslation(2,0,0).elements.slice(),beforePivot:null,world:t.mesh.matrixWorld.clone(),inverse:t.mesh.matrixWorld.clone().invert(),coordinateSpace:'world',delta:new THREE2.Matrix4().makeTranslation(2,0,0),revision:0,ready:false,released,cancel,discarded:false,abortPromise,abortResolve,releaseEvent:{type:'pointerup',pointerId:1}};if(ready)c.frameRigidActivate(s);s.ready=ready;c.setGizmoFromMatrix(s.afterGizmo);return s;}
async function test(name,fn){try{await fn();report.passed.push(name);}catch(e){report.errors.push({name,error:String(e)});}}
await test('Same Set removal/same-size replacement rejected',()=>{const {c,logs}=env(),t=fixture(c,logs),s=session(c,t);assert(c.frameRigidSelection(t)&&c.frameRigidTransactionCurrent(s));t.faces.delete(0);t.faces.add(1);assert(!c.frameRigidSelection(t)&&!c.frameRigidTransactionCurrent(s));});
await test('Replaced geometry sparse commit and ready drain rejected without mutation',async()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t),g=geometry();g.attributes.position.array[0]=90;t.mesh.geometry=g;const before=g.attributes.position.array.slice();assert.throws(()=>c.frameRigidApplySparse(t,Float32Array.of(2,0,0,3,0,0,2,1,0),Float32Array.of(0,0,1,0,0,1,0,0,1)),e=>e.name==='AbortError');c.frameRigidQueue=[s];c.frameRigidInput=s;let calls=0;const commit=c.frameRigidCommit;c.frameRigidCommit=x=>{calls++;return commit(x);};await c.frameRigidDrain();assert.equal(calls,0);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.frameRigidInput,null);assert.deepEqual(g.attributes.position.array,before);});
await test('Sticky cancel preserved through normal release',async()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t,{released:false,cancel:true});c.frameRigidQueue=[s];c.frameRigidInput=s;c.frameRigidFinish({type:'pointerup'});await c.frameRigidDrain();assert(s.cancel);assert.equal(c.undoStack.length,0);assert.deepEqual(t.pa,t.originalPositions);assert.equal(c.frameRigidQueue.length,0);});
for(const status of ['ineligible','failed'])for(const released of [false,true])await test(`${status} fallback ${released?'released':'held'} transfers CPU ownership`,async()=>{const{c,logs}=env(),t=fixture(c,logs);t.status=status;t.promise=Promise.resolve(false);const s=session(c,t,{ready:false,released});c.frameRigidQueue=[s];if(!released)c.frameRigidInput=s;await c.frameRigidDrain();assert.equal(c.frameRigidInput,null);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.frameRigidApplyDelta(new THREE2.Matrix4()),false);assert.equal(c.frameRigidFinish({type:'pointerup'}),false);assert(logs.some(x=>x[0]==='cpu-start'));if(!released){assert.equal(c.frameRigidCpuSession,s);c._gizEnd({type:'pointerup'});c.frameRigidStockEndDone();assert.equal(c.frameRigidCpuSession,null);}assert(logs.some(x=>x[0]==='cpu-end'));});
await test('Cancelled pending rejection does not enter CPU fallback',async()=>{const{c,logs}=env(),t=fixture(c,logs);t.status='ineligible';t.promise=Promise.resolve(false);const s=session(c,t,{ready:false,cancel:true});c.frameRigidQueue=[s];await c.frameRigidDrain();assert(!logs.some(x=>x[0]==='cpu-start'));assert.equal(c.frameRigidQueue.length,0);});
await test('Commit exception restores authoring/history and drains owner',async()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t);const prior={existing:true};c.undoStack.push(prior);c.pushCmd=x=>{c.undoStack.push(x);c.sceneStateToken=999;throw Error('controlled commit history failure');};c.frameRigidQueue=[s];c.frameRigidExecuting=s;await c.frameRigidDrain();assert.deepEqual(t.pa,t.originalPositions);assert.deepEqual(t.na,t.originalNormals);assert.deepEqual(c.undoStack,[prior]);assert.equal(c.sceneStateToken,1);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.frameRigidExecuting,null);assert.equal(c.frameRigidInput,null);});
for(const kind of ['scale','local','ctrl'])await test(`Pending ${kind} gesture stays behind common barrier with updated Object Move admission`,()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t,{ready:false,released:true});c.frameRigidQueue=[s];c.frameRigidDraining=true;c.gizDrag={mode:kind==='scale'?'scale':'move'};if(kind==='local')c.coordMode='object';assert.equal(c.frameRigidStart(kind==='ctrl'?{ctrlKey:true}:{}),true);assert.equal(c.frameRigidQueue.length,2);assert.equal(c.frameRigidQueue[1].kind,kind==='local'?'gpu':'cpu');assert(!logs.some(x=>x[0]==='cpu-start'));});
await test('World/renderer/lease changes invalidate immutable transaction',()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t);t.mesh.matrixWorld.elements[12]=1;assert(!c.frameRigidTransactionCurrent(s));t.mesh.matrixWorld.elements[12]=0;t.lease.generation++;assert(!c.frameRigidSource(t));t.lease.generation--;c.vpState.renderer={};assert(!c.frameRigidSource(t));});
await test('Undo hook aborts active GPU snapshot and clears input',()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t,{released:false});c.frameRigidInput=s;c.frameRigidQueue=[s];c.frameRigidBeforeHistory();assert(s.discarded&&s.cancel);assert.equal(c.frameRigidInput,null);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.gizDrag,null);assert.deepEqual(t.pa,t.originalPositions);});
await test('History accepts byte-equivalent geometry replacement only',()=>{const{c,logs}=env(),t=fixture(c,logs),g=geometry();t.mesh.geometry=g;const beforeP=t.originalPositions.slice(0,9),beforeN=t.originalNormals.slice(0,9);c.frameRigidApplySparse(t,Float32Array.of(2,0,0,3,0,0,2,1,0),beforeN,{positions:beforeP,normals:beforeN});assert.equal(g.attributes.position.array[0],2);g.attributes.position.array[9]=500;const bytes=g.attributes.position.array.slice();assert.throws(()=>c.frameRigidApplySparse(t,beforeP,beforeN,{positions:Float32Array.of(2,0,0,3,0,0,2,1,0),normals:beforeN}),e=>e.name==='AbortError');assert.deepEqual(g.attributes.position.array,bytes);});
function installStock(c,logs){Object.assign(c,{recalculateSoftSelection(){},onGizmoDragStart:f=>c._gizStart=f,onGizmoDragEnd:f=>c._gizEnd=f,capturePolyGeometries:()=>new Map([...c.pickMeshes].map(([h,m])=>[h,m.geometry.clone()])),restorePolyGeometries:before=>{for(const[h,g]of before)c.pickMeshes.get(h).geometry=g.clone();logs.push(['restore-poly']);},capturePolySelectionState:()=>({}),restorePolySelectionState(){},frameCapturePolygonDragSoft:()=>({}),frameBindPolygonDragSoft(){},capturePolySelection:()=>new Map([['h',{ids:[0,1,2]}]]),frameCurrentPolygonDragSoft:()=>({}),frameRestorePolygonDragSoft(){},gizBeforeSpline:null,gizBeforeObj:null,gizBeforeObjState:null,gizBeforeObjPivot:null,gizBeforeMulti:null,gizBeforeMultiState:null,gizBeforeSplineSel:null,gizBeforeSplinePivot:null,polyExtrudedFaces:null,uvBeforeFrame:null,hideHudLine(){},hideSnapVis(){},frameFlushPolygonGizmoMove(){logs.push(['flush-pending']);},scheduleGeneratorEvaluation(){},generatorTransformTargets:()=>[],selNodes:new Set(['h']),pivotKeyRestorePending:false,emitInfo(){},edgeBevelTool:null,edgeBevelResult:null,splineData:new Map(),objParams:new Map(),restoreSceneCommandState(){},trimCommandStack(){},afterCmd(){}});
vm.runInContext(editor.slice(editor.indexOf('function splineFocusActive() {'),editor.indexOf('function pruneSplineSelection() {')),c);
vm.runInContext(editor.slice(editor.indexOf('onGizmoDragStart((e) => {'),editor.indexOf('var frameCancelViewportMarquee=null;')),c);
vm.runInContext(editor.slice(editor.indexOf('function endGizDrag(e) {'),editor.indexOf('var _onTransform = null;')),c);
vm.runInContext(editor.slice(editor.indexOf('function undo() {'),editor.indexOf('function afterCmd(c) {')),c);
}
function committed(c,t){const s=session(c,t);c.frameRigidCommit(s);c.gizDrag=null;return c.undoStack[0];}
function activeCpuEdit(c,t,mode='scale'){if(mode==='move')t.status='ineligible';c.coordMode='object';c.gizDrag={mode};c._gizStart({type:'pointerdown',pointerId:7});const g=t.mesh.geometry;g.attributes.position.array[0]+=1;g.attributes.position.needsUpdate=true;c.setGizmoFromMatrix(new THREE2.Matrix4().makeTranslation(3,0,0).elements);return g;}
for(const mode of ['move','scale'])await test(`Actual stock ${mode} cancellation precedes Undo and late release is inert`,()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);activeCpuEdit(c,t,mode);assert(c.gizBeforePolyGeom);c.undo();assert.equal(c.gizDrag,null);assert.equal(c.gizBeforePolyGeom,null);assert.equal(c.frameRigidCpuSession,null);assert.equal(c.undoStack.length,0);assert.equal(c.redoStack[0],command);assert.deepEqual(t.mesh.geometry.attributes.position.array,t.originalPositions);const bytes=t.mesh.geometry.attributes.position.array.slice(),count=c.redoStack.length;if(c.gizDrag)c.endGizDrag({type:'pointerup',pointerId:7});assert.deepEqual(t.mesh.geometry.attributes.position.array,bytes);assert.equal(c.redoStack.length,count);c.redo();assert.equal(c.undoStack[0],command);assert.equal(t.mesh.geometry.attributes.position.array[0],2);});
for(const status of ['ineligible','failed'])await test(`Actual stock held ${status} fallback cancels before Undo`,async()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);c.gizDrag={mode:'move'};t.status=status;t.promise=Promise.resolve(false);const s=session(c,t,{ready:false,released:false});c.frameRigidQueue=[s];c.frameRigidInput=s;c.bridgeTransform=()=>{t.mesh.geometry.attributes.position.array[0]+=1;t.mesh.geometry.attributes.position.needsUpdate=true;};await c.frameRigidDrain();assert.equal(c.frameRigidCpuSession,s);assert(c.gizBeforePolyGeom);c.undo();assert.equal(c.frameRigidCpuSession,null);assert(s.cancel&&s.discarded);assert.equal(c.gizDrag,null);assert.equal(c.redoStack[0],command);assert.deepEqual(t.mesh.geometry.attributes.position.array,t.originalPositions);});
for(const direction of ['undo','redo'])await test(`Actual ${direction} retains command and external data on prewrite AbortError`,()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);if(direction==='redo')c.undo();const stack=direction==='undo'?c.undoStack:c.redoStack,other=direction==='undo'?c.redoStack:c.undoStack,g=t.mesh.geometry;g.attributes.position.array[0]+=0.5;g.attributes.position.needsUpdate=true;const bytes=g.attributes.position.array.slice(),token=c.sceneStateToken;assert.throws(()=>c[direction](),e=>e.name==='AbortError');assert.equal(stack[0],command);assert.equal(stack.length,1);assert.equal(other.length,0);assert.deepEqual(g.attributes.position.array,bytes);assert.equal(c.sceneStateToken,token);});
for(const direction of ['undo','redo'])await test(`Actual ${direction} rolls back postwrite refresh exception and preserves command`,()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);if(direction==='redo')c.undo();const stack=direction==='undo'?c.undoStack:c.redoStack,other=direction==='undo'?c.redoStack:c.undoStack,g=t.mesh.geometry,bytes=g.attributes.position.array.slice(),normals=g.attributes.normal.array.slice(),token=c.sceneStateToken,refresh=c.frameRigidRefreshSelection;c.frameRigidRefreshSelection=()=>{throw Error('controlled history refresh failure');};assert.throws(()=>c[direction](),/controlled history refresh failure/);assert.deepEqual(g.attributes.position.array,bytes);assert.deepEqual(g.attributes.normal.array,normals);assert.equal(stack[0],command);assert.equal(stack.length,1);assert.equal(other.length,0);assert.equal(c.sceneStateToken,token);c.frameRigidRefreshSelection=refresh;c[direction]();assert.equal(stack.length,0);assert.equal(other[0],command);});
for(const [label,change]of [['soft',c=>c.vertexTools.soft.active=true],['UV mode',c=>c.uvMode=true],['UV edit',c=>c.uvEdit={}],['pivot mode',c=>c.editPivot=true],['custom pivot',c=>c.polyPivotMatrix=new THREE2.Matrix4().elements],['morph',c=>c.frameMorphTag=()=>({})],['channels',c=>c.frameChannels.add('h')],['animation revision',c=>c.frameAnimationRevision++]])await test(`Held GPU ${label} context change aborts without commit`,async()=>{const{c,logs}=env(),t=fixture(c,logs),s=session(c,t,{released:false});c.frameRigidInput=s;c.frameRigidQueue=[s];change(c);assert.equal(c.frameRigidTransactionCurrent(s),false);assert.equal(c.frameRigidApplyDelta(new THREE2.Matrix4()),true);assert(s.discarded&&s.cancel);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.gizDrag,null);assert.deepEqual(t.pa,t.originalPositions);assert.equal(c.undoStack.length,0);});
const contextChanges=[['pivot',c=>c.editPivot=true,c=>c.editPivot],['UV mode',c=>c.uvMode=true,c=>c.uvMode],['UV edit',c=>c.uvEdit={qa:true},c=>!!c.uvEdit],['poly mode',c=>c.polyMode=false,c=>!c.polyMode],['spline focus',c=>{c.componentFocus='spline';c.splineMode=true;},c=>c.componentFocus==='spline'&&c.splineMode],['element mode',c=>c.polyElementMode='edge',c=>c.polyElementMode==='edge'],['soft',c=>c.vertexTools.soft.active=true,c=>c.vertexTools.soft.active],['animation revision',c=>c.frameAnimationRevision++,c=>c.frameAnimationRevision===2],['channels',c=>c.frameChannels.add('h'),c=>c.frameChannels.has('h')]];
for(const [name,change,preserved]of contextChanges)for(const boundary of ['undo','release'])await test(`Stock CPU ${name} context change uses start-context rollback on ${boundary}`,()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);activeCpuEdit(c,t,'scale');assert(c.gizDrag._frameAuthoringContext.component);const beforeDrag=c.gizBeforePolyGeom.get('h').attributes.position.array.slice();change(c);assert(c.frameRigidStockContextChanged(c.gizDrag));if(boundary==='undo')c.undo();else c.endGizDrag({type:'pointerup',pointerId:7});assert.equal(c.gizDrag,null);assert.equal(c.gizBeforePolyGeom,null);assert.equal(c.frameRigidCpuSession,null);assert(preserved(c));assert.deepEqual(t.mesh.geometry.attributes.position.array,boundary==='undo'?t.originalPositions:beforeDrag);assert.equal(boundary==='undo'?c.redoStack[0]:c.undoStack[0],command);assert.equal(c.undoStack.length+c.redoStack.length,1);assert.equal(c.frameRigidCancellingStock,false);assert.equal(c.frameRigidFallthrough,false);const data=t.mesh.geometry.attributes.position.array.slice();if(c.gizDrag)c.endGizDrag({type:'pointerup',pointerId:7});assert.deepEqual(t.mesh.geometry.attributes.position.array,data);});
for(const mode of ['move','scale'])for(const direction of ['undo','redo'])await test(`Stock ${mode} plus P plus ${direction} restores history and retains current pivot mode`,()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);if(direction==='redo')c.undo();activeCpuEdit(c,t,mode);c.editPivot=true;c[direction]();assert.equal(c.editPivot,true);assert.equal(c.gizDrag,null);assert.equal(c.gizBeforePolyGeom,null);assert.equal(c.frameRigidCpuSession,null);assert.equal(direction==='undo'?c.redoStack[0]:c.undoStack[0],command);assert.equal(t.mesh.geometry.attributes.position.array[0],direction==='undo'?0:2);});
for(const status of ['ineligible','failed'])for(const boundary of ['undo','release'])await test(`Held ${status} CPU fallback plus P rolls back at ${boundary}`,async()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const command=committed(c,t);c.gizDrag={mode:'move'};t.status=status;t.promise=Promise.resolve(false);const s=session(c,t,{ready:false,released:false});c.frameRigidQueue=[s];c.frameRigidInput=s;c.bridgeTransform=()=>{t.mesh.geometry.attributes.position.array[0]+=1;t.mesh.geometry.attributes.position.needsUpdate=true;};await c.frameRigidDrain();assert.equal(c.frameRigidCpuSession,s);assert(c.gizDrag._frameAuthoringContext.component);c.editPivot=true;if(boundary==='undo')c.undo();else c.endGizDrag({type:'pointerup',pointerId:7});assert.equal(c.frameRigidCpuSession,null);assert.equal(c.gizDrag,null);assert.equal(c.gizBeforePolyGeom,null);assert.equal(c.editPivot,true);assert.equal(boundary==='undo'?c.redoStack[0]:c.undoStack[0],command);assert.equal(t.mesh.geometry.attributes.position.array[0],boundary==='undo'?0:2);});
await test('Queued GPU commit then held CPU gesture plus P cancels only active CPU work before Undo',async()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);const first=session(c,t,{ready:true,released:true});const drag={mode:'scale'};c.gizDrag=drag;const second=session(c,t,{ready:false,released:false,kind:'cpu'});second.drag=drag;c.frameRigidQueue=[first,second];c.frameRigidInput=second;c.bridgeTransform=()=>{t.mesh.geometry.attributes.position.array[0]+=1;t.mesh.geometry.attributes.position.needsUpdate=true;};await c.frameRigidDrain();assert(first.committed);assert.equal(c.undoStack.length,1);assert.equal(c.frameRigidQueue.length,0);assert.equal(c.frameRigidCpuSession,second);assert.equal(t.mesh.geometry.attributes.position.array[0],3);c.editPivot=true;c.undo();assert.equal(c.undoStack.length,0);assert.equal(c.redoStack.length,1);assert.equal(c.frameRigidCpuSession,null);assert.equal(c.gizDrag,null);assert.equal(c.gizBeforePolyGeom,null);assert.deepEqual(t.mesh.geometry.attributes.position.array,t.originalPositions);assert.equal(c.editPivot,true);});
function positionOracle(t,delta){const out=t.originalPositions.slice(),inv=t.mesh.matrixWorld.clone().invert(),base=new THREE2.Vector3(),moved=new THREE2.Vector3();for(const id of t.ids){base.fromArray(t.originalPositions,id*3);moved.copy(base).applyMatrix4(t.mesh.matrixWorld).applyMatrix4(delta).applyMatrix4(inv);base.lerp(moved,1);out.set(base.toArray(),id*3);}return out;}
function extentOracle(t,positions,frame){const inv=frame.clone().invert(),lo=new THREE2.Vector3(Infinity,Infinity,Infinity),hi=new THREE2.Vector3(-Infinity,-Infinity,-Infinity),p=new THREE2.Vector3();for(const id of t.ids){p.fromArray(positions,id*3).applyMatrix4(t.mesh.matrixWorld).applyMatrix4(inv);lo.min(p);hi.max(p);}return hi.sub(lo);}
for(const reflected of [false,true])for(const customPivot of [false,true])await test(`Default Object Move exact ordered preview/commit/CM/Undo (reflection=${reflected},customPivot=${customPivot})`,async()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);t.idSet=new Set(t.ids);t.mesh.matrixWorld.compose(new THREE2.Vector3(37,-18,12),new THREE2.Quaternion().setFromEuler(new THREE2.Euler(.4,-.7,.2)),new THREE2.Vector3(reflected?-2:2,2,2));c.frameRigidExactBounds(t);t.gpu.submit=()=>Promise.resolve({status:'cancelled'});c.coordMode='object';c.gizDrag={mode:'move'};const g0=new THREE2.Matrix4().makeRotationFromEuler(new THREE2.Euler(.3,.2,-.6)).setPosition(3,4,-2);if(customPivot)c.polyPivotMatrix=g0.elements.slice();c.setGizmoFromMatrix(g0.elements);c._gizStart({type:'pointerdown',pointerId:11});await new Promise(setImmediate);const active=c.frameRigidInput;assert(active&&active.ready&&active.kind==='gpu');assert.equal(active.coordinateSpace,'object');const g1=g0.clone();g1.elements[12]+=.375;g1.elements[13]-=.625;g1.elements[14]+=.125;const delta=g1.clone().multiply(g0.clone().invert()),expected=positionOracle(t,delta);c.setGizmoFromMatrix(g1.elements);assert(c.frameRigidApplyDelta(delta));for(const id of t.ids)for(let j=0;j<3;j++)assert.equal(t.adapter.positionView(id,j),expected[id*3+j]);c.frameRigidFinish({type:'pointerup',pointerId:11});await new Promise(setImmediate);c.gizDrag=null;assert.equal(c.undoStack.length,1);assert.deepEqual(t.pa,expected);assert.deepEqual(t.na,t.originalNormals);assert.deepEqual(t.ia,t.indexSeed);assert.deepEqual(t.pa.slice(9),t.originalPositions.slice(9));assert.equal(c.frameRigidQueue.length,0);assert.equal(c.frameRigidInput,null);assert.deepEqual(c.polyPivotMatrix,customPivot?g1.elements:null);c.polySelectedVertexIds=()=>t.idSet;vm.runInContext(editor.slice(editor.indexOf('function polyExtentInFrame(frame) {'),editor.indexOf('function basisFromNormal(')),c);for(const frame of [new THREE2.Matrix4(),g1])assert.deepEqual(c.polyExtentInFrame(frame).toArray(),extentOracle(t,expected,frame).toArray());c.undo();assert.deepEqual(t.mesh.geometry.attributes.position.array,t.originalPositions);assert.deepEqual(t.mesh.geometry.attributes.normal.array,t.originalNormals);c.redo();assert.deepEqual(t.mesh.geometry.attributes.position.array,expected);assert.deepEqual(t.mesh.geometry.attributes.normal.array,t.originalNormals);});
await test('Default Object Move active Undo cancels preview and ignores late release',async()=>{const{c,logs}=env(),t=fixture(c,logs);installStock(c,logs);committed(c,t);c.coordMode='object';c.gizDrag={mode:'move'};t.gpu.submit=()=>Promise.resolve({status:'cancelled'});c._gizStart({type:'pointerdown',pointerId:11});await new Promise(setImmediate);assert(c.frameRigidInput?.ready);c.frameRigidApplyDelta(new THREE2.Matrix4().makeTranslation(3,2,1));c.undo();assert.equal(c.frameRigidInput,null);assert.equal(c.gizDrag,null);assert.deepEqual(t.pa,t.originalPositions);const count=c.redoStack.length;if(c.gizDrag)c.endGizDrag({type:'pointerup',pointerId:11});assert.equal(c.redoStack.length,count);assert.deepEqual(t.pa,t.originalPositions);});
for(const mode of ['rotate','screenRotate','scale','scaleU'])await test(`Object ${mode} remains outside new direct GPU admission`,()=>{const{c,logs}=env();fixture(c,logs);c.coordMode='object';c.gizDrag={mode};assert.equal(c.frameRigidStart({pointerId:1}),false);assert.equal(c.frameRigidQueue.length,0);});
await test('Nonuniform Object Move keeps CPU transaction classification',()=>{const{c,logs}=env(),t=fixture(c,logs);t.mesh.matrixWorld.makeScale(2,1,1);c.coordMode='object';c.gizDrag={mode:'move'};c.frameRigidDraining=true;assert(c.frameRigidStart({pointerId:1}));assert.equal(c.frameRigidInput.kind,'cpu');});
console.log(JSON.stringify(report,null,2));if(report.errors.length)process.exitCode=1;
