'use strict';
// Exact dyadic predicates: no tolerance, welding or displacement of source points.
function exactIntegers(ring){const view=new DataView(new ArrayBuffer(8));const q=ring.map(p=>p.map(x=>{if(!Number.isFinite(x))throw Error('nonfinite source');if(x===0)return{n:0n,e:0};view.setFloat64(0,x);const b=view.getBigUint64(0),E=Number((b>>52n)&2047n);let n=b&4503599627370495n;if(E)n|=4503599627370496n;if(b>>63n)n=-n;return{n,e:E?E-1075:-1074};}));const nz=q.flat().filter(x=>x.n);const e=nz.length?nz.reduce((m,x)=>Math.min(m,x.e),Infinity):0;return q.map(p=>p.map(x=>x.n?x.n<<BigInt(x.e-e):0n));}
function canonicalRing(ring){if(!Array.isArray(ring)||ring.length<3||ring.length>4096||ring.some(p=>!Array.isArray(p)||p.length!==2))throw Error('invalid source ring');const I=exactIntegers(ring),sub=(a,b)=>a.map((v,k)=>v-b[k]),cross=(a,b)=>a[0]*b[1]-a[1]*b[0],dot=(a,b)=>a[0]*b[0]+a[1]*b[1];const keep=[];for(let i=0;i<I.length;i++){const a=sub(I[i],I[(i+I.length-1)%I.length]),b=sub(I[(i+1)%I.length],I[i]);if(dot(a,a)===0n||dot(b,b)===0n)throw Error('duplicate source vertex requires topology diagnosis');if(cross(a,b)!==0n||dot(a,b)<=0n)keep.push(i);}if(keep.length<3)throw Error('degenerate source ring');const chains=keep.map((a,i)=>{const z=keep[(i+1)%keep.length],ids=[];let j=a;while(j!==z){ids.push(j);j=(j+1)%ring.length;}return ids;});return{ring:keep.map(i=>ring[i].slice()),sourceVertices:keep,sourceEdgeChains:chains};}
function createCore(){const {placement}=require('./adapter.cjs').load();return{sliceContours(rings,W=1,count=1,options={}){if(!(W>0)||!Number.isFinite(W))throw Error('invalid nominal width');if(!Array.isArray(rings)||rings.length===0||rings.length>64)throw Error('invalid source ring set');if(!Number.isInteger(count)||count<1||count>64)throw Error('invalid perimeter count');const inherited=options.incomingDeviationUpperBoundMM??0;if(!Number.isFinite(inherited)||inherited<0||inherited>.02*W)throw Error('invalid inherited accuracy budget');let normalized=rings.map(canonicalRing),roundingDiagnostic=null;
if(options.roundingNormalization===true){const {normalizeRoundedRing}=require('./rounded-normalization.cjs'),{topologySignature}=require('./topology.cjs');try{const before=topologySignature(rings),candidate=rings.map((r,i)=>normalizeRoundedRing(r,W,canonicalRing,rings,i));if(topologySignature(candidate.map(q=>q.ring))!==before)throw Error('changed-source-nesting');if(inherited+Math.max(...candidate.map(q=>q.maximumDeviationUpperBoundMM))>.02*W)throw Error('source-accuracy-budget-exhausted');normalized=candidate;}catch(e){roundingDiagnostic=e.message;}}
const geometry=placement(normalized.map(q=>q.ring),W,count),sourceDeviation=Math.max(...normalized.map(q=>q.maximumDeviationUpperBoundMM??0)),sourceProvenance=require('./provenance.cjs').collectMappings(geometry,normalized,rings,require('./source-binding.cjs').resolveIncidence(rings,options.sourceFaceIncidence,options.sourceGeneration));
return{geometry,source:rings.map(r=>r.map(p=>p.slice())),canonicalSource:normalized.map(q=>q.ring),sourceEdgeChains:normalized.map(q=>q.sourceEdgeChains),sourceProvenance,roundingDiagnostic,metadataCoordinateSpace:'canonicalSource; exact original interval partitions in sourceProvenance',maximumSourceDeviationMM:sourceDeviation,accuracyBudget:{limitMM:.02*W,inheritedUpperBoundMM:inherited,sourceUpperBoundMM:sourceDeviation,remainingTrajectoryBudgetMM:.02*W-inherited-sourceDeviation,wholeTrajectoryDeviationCertified:false},originalSourcePreserved:true,physicalPrintValidated:false};}};}
// The host passes its existing shared heavy scheduler; this module creates no pool.
async function sliceWithScheduler(core,input,scheduler,signal){if(!scheduler||typeof scheduler.run!=='function')throw Error('shared Frame scheduler required');return scheduler.run({kind:'slice-contours',signal},()=>{if(signal?.aborted)throw Error('slice cancelled');return core.sliceContours(input.rings,input.W,input.count);});}
module.exports={exactIntegers,canonicalRing,createCore,sliceWithScheduler};



