'use strict';
// Independent exact section of finite Float64 triangles, physical coordinates Z up.
// Certificates are rederived from the mesh; neither face IDs nor angles are trusted.
const R=require('./rational.cjs'),crypto=require('crypto');
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const key=p=>p.map(R.str).join(','),abs=q=>q.n<0n?R.rat(-q.n,q.d):q;
function nextUp(x){if(!Number.isFinite(x)||x<0)throw Error('invalid nonnegative bound');if(!x)return Number.MIN_VALUE;const b=new DataView(new ArrayBuffer(8));b.setFloat64(0,x);b.setBigUint64(0,b.getBigUint64(0)+1n);return b.getFloat64(0);}
function upper(q){let x=R.number(q);if(!Number.isFinite(x))throw Error('unrepresentable section accuracy');while(R.cmp(R.exact(x),q)<0)x=nextUp(x);return x;}
function validateMesh(mesh){if(!mesh||!Number.isSafeInteger(mesh.generation)||mesh.generation<0||!Array.isArray(mesh.vertices)||!Array.isArray(mesh.faces)||mesh.faces.length>4096||mesh.vertices.length>16384)throw Error('invalid-or-out-of-scope-mesh');for(const p of mesh.vertices)if(!Array.isArray(p)||p.length!==3||p.some(v=>!Number.isFinite(v)))throw Error('invalid source vertex');return hash({vertices:mesh.vertices,faces:mesh.faces,generation:mesh.generation});}
function triangle(mesh,face,z){const ids=mesh.faces[face];if(!Array.isArray(ids)||ids.length!==3||ids.some(i=>!Number.isSafeInteger(i)||i<0||i>=mesh.vertices.length))return{diagnostic:'invalid-face-indices',faceId:face};const P=ids.map(i=>mesh.vertices[i].map(R.exact)),u=P[1].map((v,k)=>R.sub(v,P[0][k])),v=P[2].map((v,k)=>R.sub(v,P[0][k])),N=[R.sub(R.mul(u[1],v[2]),R.mul(u[2],v[1])),R.sub(R.mul(u[2],v[0]),R.mul(u[0],v[2])),R.sub(R.mul(u[0],v[1]),R.mul(u[1],v[0]))];if(N.every(q=>!q.n))return{diagnostic:'degenerate-face',faceId:face};if(P.every(p=>R.cmp(p[2],z)===0))return{diagnostic:'coplanar-face',faceId:face};const hits=new Map();for(let i=0;i<3;i++){const a=P[i],b=P[(i+1)%3],sa=R.cmp(a[2],z),sb=R.cmp(b[2],z);if(!sa)hits.set(key(a),a);if(sa*sb<0){const t=R.div(R.sub(z,a[2]),R.sub(b[2],a[2])),p=a.map((q,k)=>R.add(q,R.mul(t,R.sub(b[k],q))));hits.set(key(p),p);}}if(hits.size<2)return{diagnostic:hits.size?'vertex-touch':null,faceId:face};if(hits.size!==2)return{diagnostic:'ambiguous-triangle-section',faceId:face};let m=N.map(abs).reduce((a,b)=>R.cmp(a,b)>0?a:b),n=N.map(q=>R.number(R.div(q,m))),angle=Math.asin(Math.max(0,Math.min(1,-n[2]/Math.hypot(...n))))*180/Math.PI;return{points:[...hits.values()].map(p=>p.slice(0,2)),faceId:face,sourceAngle:angle,exactNormal:N.map(R.str),vertexIds:ids.slice()};}
function sectionMesh(mesh,z){const meshSignature=validateMesh(mesh);if(!Number.isFinite(z))throw Error('invalid section plane');const plane=R.exact(z),segments=new Map(),diagnostics=[];for(let face=0;face<mesh.faces.length;face++){const q=triangle(mesh,face,plane);if(q.diagnostic)diagnostics.push({faceId:face,reason:q.diagnostic});if(!q.points)continue;const endpoints=q.points.map(key),ordered=endpoints.slice().sort(),id=ordered.join('|');let edge=segments.get(id);if(!edge){edge={id,keys:endpoints,points:q.points,faces:[]};segments.set(id,edge);}edge.faces.push({faceId:face,sourceAngle:q.sourceAngle,exactNormal:q.exactNormal,vertexIds:q.vertexIds});}
 for(const e of segments.values())if(new Set(e.faces.map(f=>f.sourceAngle)).size>1)diagnostics.push({reason:'conflicting-section-face-inclinations',sourceFaceIds:e.faces.map(f=>f.faceId),exactSegment:e.points.map(p=>p.map(R.str))});const adj=new Map();for(const e of segments.values())for(const k of e.keys){if(!adj.has(k))adj.set(k,[]);adj.get(k).push(e);}const seen=new Set(),rings=[],edgeFaces=[],exactRings=[],unresolvedComponents=[];let conversion=R.zero;
 for(const start of [...adj.keys()].sort()){if(seen.has(start))continue;const stack=[start],component=[];while(stack.length){const k=stack.pop();if(seen.has(k))continue;seen.add(k);component.push(k);for(const e of adj.get(k))stack.push(e.keys.find(x=>x!==k));}const bad=component.filter(k=>adj.get(k).length!==2);if(bad.length){unresolvedComponents.push({reason:'non-two-valent-section-component',vertices:component.length,segments:[...new Set(component.flatMap(k=>adj.get(k).map(e=>e.id)))].map(id=>{const e=segments.get(id);return{exactPoints:e.points.map(p=>p.map(R.str)),sourceFaces:e.faces};}),degrees:bad.map(k=>({exactPoint:k,degree:adj.get(k).length}))});continue;}
  const points=[],faces=[];let at=start,prior=null;do{const choices=adj.get(at).filter(e=>e!==prior).sort((a,b)=>a.id.localeCompare(b.id)),e=choices[0],i=e.keys.indexOf(at);points.push(e.points[i]);faces.push(e.faces);prior=e;at=e.keys[1-i];if(points.length>4096)throw Error('bounded-section-ring');}while(at!==start);if(points.length<3){unresolvedComponents.push({reason:'degenerate-section-loop',vertices:points.length});continue;}const ring=points.map(p=>p.map(R.number));for(let i=0;i<points.length;i++){const error=points[i].map((q,k)=>abs(R.sub(q,R.exact(ring[i][k])))).reduce(R.add,R.zero);if(R.cmp(error,conversion)>0)conversion=error;}if(ring.some((p,i)=>p.every((v,k)=>v===ring[(i+1)%ring.length][k]))){unresolvedComponents.push({reason:'unrepresentable-section-edge',vertices:points.length,exactPoints:points.map(p=>p.map(R.str)),sourceFaces:faces});continue;}rings.push(ring);exactRings.push(points.map(p=>p.map(R.str)));edgeFaces.push(faces.map((fs,i)=>fs.map(f=>({...f,sourceStart:ring[i].slice(),sourceEnd:ring[(i+1)%ring.length].slice(),exactSectionStart:points[i].map(R.str),exactSectionEnd:points[(i+1)%ring.length].map(R.str)}))));}
 const topology=require('./section-topology.cjs').diagnoseExactTopology(exactRings);diagnostics.push(...topology.diagnostics);const out={kind:'verified-mesh-section',meshSignature,sourceGeneration:mesh.generation,z,rings,edgeFaces,exactRings,diagnostics,unresolvedComponents,conversionUpperBoundMM:upper(conversion),conversionExactUpperBound:R.str(conversion),angleConvention:'physical-Z-up asin(max(0,-normalZ/length)), actual oriented triangle',closedComponentsQualified:unresolvedComponents.length===0&&topology.complete&&!diagnostics.some(q=>['self-contact-in-exact-section','cross-component-contact-in-exact-section','section-topology-work-budget','coplanar-face','conflicting-section-face-inclinations','ambiguous-triangle-section','invalid-face-indices','degenerate-face'].includes(q.reason))};out.sectionSignature=hash(out);return out;}
function verifySection(mesh,section){const current=sectionMesh(mesh,section?.z);if(hash(current)!==hash(section))throw Error('stale-or-forged-mesh-section');return current;}
module.exports={sectionMesh,verifySection,triangle,validateMesh,upper,nextUp,hash};
