import fs from 'node:fs';import {fileURLToPath} from 'node:url';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('.',import.meta.url)),ts=createRequire(import.meta.url)(process.env.FRAME_TYPESCRIPT||'typescript'),sha=b=>createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'build-manifest.json'))),spec=JSON.parse(fs.readFileSync(path.join(root,manifest.baseExtraction))),input=fs.readFileSync(path.join(root,'..',manifest.productionEditor));
assert.equal(ts.version,manifest.typescript,'Use the pinned TypeScript version');assert.equal(input.length,spec.beforeBytes);assert.equal(sha(input),spec.beforeSHA256);
const lines=input.toString('utf8').match(/[^\n]*\n|[^\n]+$/g)||[];for(const e of spec.operations.toReversed())lines.splice(e.startLine,e.deleteLines,...e.insert);const base=lines.join('');assert.equal(Buffer.byteLength(base),spec.afterBytes);assert.equal(sha(base),spec.afterSHA256);
assert.equal(sha(base),'0e51597ef74e6e6583d18fca9ff1725cc4bff5edde26ef7400d71ae9986d609f');let source=base;const edits=[];
function once(name,before,after){assert.equal(source.split(before).length-1,1,name);source=source.replace(before,after);edits.push({name,before,after});}
once('preview start or queued preparation','onGizmoDragStart((e) => {','onGizmoDragStart((e) => {\n  if(gizDrag)gizDrag._frameAuthoringPointerId=e?.pointerId;\n  if(frameRigidStart(e))return;');
once('authoring synchronization on release','onGizmoDragEnd((event) => {','onGizmoDragEnd((event) => {\n  if(frameRigidFinish(event))return;');
once('GPU delta preview','function applyPolyDelta(delta, snap) {','function applyPolyDelta(delta, snap) {\n  if(frameRigidApplyDelta(delta))return;');
once('save applied preview coordinates','function packedGeometryAttribute(a){','function packedGeometryAttribute(a){\n  const rigid=frameNative.captureRigidAuthoringAttribute(a);if(rigid)return rigid;');
once('snapshot applied preview coordinates','function framePolygonAttributeArray(a) {','function framePolygonAttributeArray(a) {\n  const rigid=frameNative.captureRigidAuthoringAttribute(a);if(rigid)return rigid;');
once('stable isolated authoring selection IDs','function polySelectedVertexIds(h) {','function polySelectedVertexIds(h) {\n  const rigid=frameRigidSelectedIDs(h);if(rigid)return rigid;');
once('cooperative stable isolated IDs','function* framePolySelectedVertexIdsWork(h,items=polySelection.items,exact=polyExactEdgeVertices) {','function* framePolySelectedVertexIdsWork(h,items=polySelection.items,exact=polyExactEdgeVertices) {\n  const rigid=items===polySelection.items&&!exact?.has(h)?frameRigidSelectedIDs(h):null;if(rigid)return new Set(rigid);');
once('cached current world bounds','function polySelectionBounds() {','function polySelectionBounds() {\n  const rigid=frameRigidBounds();if(rigid)return rigid;');
once('coordinate-basis guarded extent','function polyExtentInFrame(frame) {','function polyExtentInFrame(frame) {\n  const rigid=frameRigidExtent(frame);if(rigid)return rigid;');
const ast=ts.createSourceFile('editor.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),f=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='frameInstallPolySelectionBuffers');assert(f);const before=f.getText(ast),after=before.slice(0,-1)+'  frameRigidSchedulePrepare();\n}';once('prepare off the gesture path',before,after);
const helper=fs.readFileSync(root+'/'+'rigid-component-preview.mjs','utf8');once('island transaction helpers','onGizmoDragStart((e) => {',helper+'\nonGizmoDragStart((e) => {');if(helper.includes('function frameRigidCaptureDragContext(')){once('capture start context for every stock and queued component drag','  if(gizDrag)gizDrag._frameAuthoringPointerId=e?.pointerId;','  frameRigidCaptureDragContext(e);');once('cancel CPU release in its captured start context','  if(frameRigidFinish(event))return;','  if(frameRigidFinish(event))return;\n  if(frameRigidEndChangedStockContext(event))return;');once('worker-safe applied position snapshot','function packedGeometryAttribute(a){\n  const rigid=frameNative.captureRigidAuthoringAttribute(a);if(rigid)return rigid;','function packedGeometryAttribute(a){\n  const rigid=typeof frameNative!==\'undefined\'?frameNative.captureRigidAuthoringAttribute(a):null;if(rigid)return rigid;');}if(true){once('Undo pending authoring barrier','function undo() {','function undo() {\n  frameRigidBeforeHistory();');once('Redo pending authoring barrier','function redo() {','function redo() {\n  frameRigidBeforeHistory();');const a=ts.createSourceFile('with-barrier.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),call=a.statements.find(n=>ts.isExpressionStatement(n)&&ts.isCallExpression(n.expression)&&n.expression.expression.getText(a)==='onGizmoDragEnd'),body=call.expression.arguments[0].body,bodyText=body.getText(a),guard='\n  if(frameRigidFinish(event))return;';assert(bodyText.includes(guard));const rest=bodyText.slice(1,-1).replace(guard,'');once('CPU fallback end cleanup',bodyText,'{'+guard+'\n  try{'+rest+'\n  }finally{frameRigidStockEndDone();}\n}');}const parsed=ts.createSourceFile('editor-candidate.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);assert.equal(parsed.parseDiagnostics.length,0);assert(parsed.statements.some(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='bridgeTransform'),'Required stock fallback function');
if(helper.includes('frameRigidNativePreserveAuthoredGeometry')){
once('native worker installs serialized authored normals','g.setIndex(new THREE2.BufferAttribute(data.indices,1));g.computeBoundingBox();','g.setIndex(new THREE2.BufferAttribute(data.indices,1));if(data.normals)g.setAttribute(\'normal\',new THREE2.BufferAttribute(data.normals,3));g.computeBoundingBox();');
once('native worker preserves authored indexed geometry','normalizeCreaseTopology(mesh,false);const out=mesh.geometry;','if(!data.normals)normalizeCreaseTopology(mesh,false);const out=mesh.geometry;');
once('native main path installs authored normals','g.setIndex(new THREE2.BufferAttribute(d.indices.slice(),1));for(const [k,a,size]','g.setIndex(new THREE2.BufferAttribute(d.indices.slice(),1));g.setAttribute(\'normal\',new THREE2.BufferAttribute(d.normals.slice(),3));markPolygonCreaseGeometry(g);for(const [k,a,size]');
}
if(helper.includes('frameRigidNativeWorkerClosureComplete')){
once('worker-safe exact geometry snapshot helper','function framePolygonAttributeArray(a) {\n  const rigid=frameNative.captureRigidAuthoringAttribute(a);if(rigid)return rigid;','function framePolygonAttributeArray(a) {\n  const rigid=typeof frameNative!==\'undefined\'?frameNative.captureRigidAuthoringAttribute(a):null;if(rigid)return rigid;');
once('native worker carries exact geometry snapshot dependency',' const packedGeometryAttribute=${packedGeometryAttribute.toString()};',' const packedGeometryAttribute=${packedGeometryAttribute.toString()};\n const framePolygonAttributeArray=${framePolygonAttributeArray.toString()};');
}
if(true){const scoped=(fn,name,before,after)=>{const a=ts.createSourceFile('history-scope.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),f=a.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===fn);assert(f,fn);const b=f.getText(a);assert.equal(b.split(before).length-1,1,name);once(name,b,b.replace(before,after));};scoped('undo','exception-safe Undo stack transfer','  let c = undoStack.pop();','  let c = undoStack.at(-1);');scoped('undo','Undo dequeue after successful command','  redoStack.push(c);trimCommandStack(redoStack);afterCmd(c);','  undoStack.pop();redoStack.push(c);trimCommandStack(redoStack);afterCmd(c);');scoped('redo','exception-safe Redo stack transfer','  let c = redoStack.pop();','  let c = redoStack.at(-1);');scoped('redo','Redo dequeue after successful command',"c.redo();restoreSceneCommandState(c,'after');undoStack.push(c)","c.redo();restoreSceneCommandState(c,'after');redoStack.pop();undoStack.push(c)");}
const finalParsed=ts.createSourceFile('editor-final.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);assert.equal(finalParsed.parseDiagnostics.length,0);assert(process.argv[2],'Pass a new output file outside the repository');const output=path.resolve(process.argv[2]),repo=path.resolve(root,'..');assert(output!==repo&&!output.startsWith(repo+path.sep),'Output must be outside the checkout');fs.writeFileSync(output,source,{flag:'wx'});console.log(JSON.stringify({pass:true,bytes:Buffer.byteLength(source),sha256:sha(source),matchesPinnedRelease:sha(source)===manifest.productionSHA256,edits:edits.length}));
